name: js-langchain-react CI

on:
  push:
    paths:
      - 'js-langchain-react/**'
      - '.github/workflows/js-langchain-react.yml'
  pull_request:
    paths:
      - 'js-langchain-react/**'
      - '.github/workflows/js-langchain-react.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js-langchain-react

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test || echo "No tests specified"

    - name: Upload artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: js-langchain-react-artifacts
        path: js-langchain-react/build
