name: py-pyramid-agno CI

on:
  push:
    paths:
      - 'py-pyramid-agno/**'
      - '.github/workflows/py-pyramid-agno.yml'
  pull_request:
    paths:
      - 'py-pyramid-agno/**'
      - '.github/workflows/py-pyramid-agno.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: py-pyramid-agno

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run tests
      run: |
        if [ -d "tests" ]; then
          pytest || echo "Pytest execution failed"
        else
          echo "No tests found, skipping tests"
        fi

    - name: Create package
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        mkdir -p dist
        python setup.py sdist

    - name: Upload artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: py-pyramid-agno-artifacts
        path: py-pyramid-agno/dist
